// src/App.jsx — Generated by VIA for: “Build a full-stack note-taking application with user authentication, create/edit/delete notes, responsive dashboard, and deploy,
import { useState, useEffect } from "react";
import { getStats, getItems } from "./api.js";

const BAR_COLORS = ["#10b981", "#6366f1","#f59e0b","#10b981","#ef4444","#8b5cf6"];

function BarChart({ data }) {
  const max = Math.max(...data.map(d => d.value), 1);
  return (
    <div className="space-y-2">
      {data.map((d, i) => (
        <div key={i} className="flex items-center gap-3">
          <span className="text-xs text-gray-500 w-20 text-right shrink-0">{d.label}</span>
          <div className="flex-1 bg-gray-100 rounded-full h-6 overflow-hidden">
            <div className="h-full rounded-full flex items-center justify-end pr-2 transition-all duration-700"
              style={{ width: `${(d.value/max)*100}%`, backgroundColor: BAR_COLORS[i % BAR_COLORS.length] }}>
              <span className="text-xs text-white font-semibold">{d.value}</span>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}

export default function App() {
  const [stats, setStats] = useState({ total:0, active:0 });
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [period, setPeriod] = useState("week");

  useEffect(() => {
    Promise.all([
      getStats().then(r => r.data).catch(() => ({ total: 0, active: 0 })),
      getItems().then(r => Array.isArray(r.data) ? r.data : r.data?.items ?? []).catch(() => []),
    ]).then(([s, i]) => { setStats(s); setItems(i); setLoading(false); });
  }, []);

  const MOCK_TREND = [
    { label:"Mon", value:42 }, { label:"Tue", value:68 }, { label:"Wed", value:55 },
    { label:"Thu", value:91 }, { label:"Fri", value:74 }, { label:"Sat", value:39 }, { label:"Sun", value:57 },
  ];

  const statusData = ["active","pending","done","inactive"].map(s => ({
    label: s.charAt(0).toUpperCase() + s.slice(1),
    value: items.filter(i => i.status === s).length,
  })).filter(d => d.value > 0);

  return (
    <div className="min-h-screen" style={{ backgroundColor: "#f0fdf4" }}>
      <nav className="bg-white border-b border-gray-100 shadow-sm sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3"><span className="text-2xl">📊</span><span className="font-bold text-gray-900">Build A Full Stack Note Taking Application With</span></div>
          <div className="flex gap-2">
            {["week","month","year"].map(p => (
              <button key={p} onClick={() => setPeriod(p)}
                className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-all ${period===p ? "text-white" : "text-gray-500 bg-white border border-gray-200"}`}
                style={{ backgroundColor: period===p ? "#10b981" : undefined }}>
                {p.charAt(0).toUpperCase()+p.slice(1)}
              </button>
            ))}
          </div>
        </div>
      </nav>
      <main className="max-w-7xl mx-auto px-6 py-8 space-y-6">
        <h1 className="text-2xl font-bold text-gray-900">Build A Full Stack Note Taking Application With</h1>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            ["Total Records", stats.total ?? items.length ?? 0, "📦", "blue"],
            ["Active",        stats.active ?? items.filter(i=>i.status==="active").length, "✅", "green"],
            ["This Period",   Math.floor(Math.random()*40)+10, "📈", "purple"],
            ["Growth",        "+12%", "🚀", "amber"],
          ].map(([label, val, ic, color]) => (
            <div key={label} className={`card bg-gradient-to-br ${
              color==="blue" ? "from-blue-50 to-blue-100/50 border-blue-200" :
              color==="green"? "from-green-50 to-green-100/50 border-green-200" :
              color==="purple"?"from-purple-50 to-purple-100/50 border-purple-200":
                               "from-amber-50 to-amber-100/50 border-amber-200"
            }`}>
              <p className="text-2xl mb-1">{ic}</p>
              <p className="text-2xl font-bold text-gray-900">{loading ? "…" : val}</p>
              <p className="text-xs text-gray-500 mt-1">{label}</p>
            </div>
          ))}
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="card space-y-4">
            <h2 className="font-semibold text-gray-800">Activity Trend</h2>
            <BarChart data={MOCK_TREND} />
          </div>
          <div className="card space-y-4">
            <h2 className="font-semibold text-gray-800">Status Breakdown</h2>
            {statusData.length > 0
              ? <BarChart data={statusData} />
              : <p className="text-gray-400 text-sm py-8 text-center">No data yet</p>
            }
          </div>
        </div>
        {items.length > 0 && (
          <div className="card overflow-hidden p-0">
            <div className="px-5 py-4 border-b border-gray-100"><h2 className="font-semibold text-gray-800">Recent Records</h2></div>
            <table className="w-full text-sm">
              <thead className="bg-gray-50"><tr>
                <th className="px-5 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Title</th>
                <th className="px-5 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Status</th>
                <th className="px-5 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Created</th>
              </tr></thead>
              <tbody className="divide-y divide-gray-50">
                {items.slice(0,8).map(item => (
                  <tr key={item.id ?? item._id} className="hover:bg-gray-50/50">
                    <td className="px-5 py-3 font-medium text-gray-900">{item.title}</td>
                    <td className="px-5 py-3"><span className="text-xs px-2 py-1 rounded-full bg-green-100 text-green-700">{item.status || "active"}</span></td>
                    <td className="px-5 py-3 text-gray-400">{item.created_at ? new Date(item.created_at).toLocaleDateString() : "—"}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </main>
    </div>
  );
}
